stages:
  - sync

sync_to_github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - printf '%s' "$GITHUB_DEPLOY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
  script:
    - git clone --mirror https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/k123qwerty-group/rms.git
    - cd rms.git
    - git push --mirror git@github.com:imabot2604/rms.git
  only:
    - branches
